# Generated by Django 4.1.1 on 2022-09-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_alter_link_truncated_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='transition',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
